### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by andcl** [yabhq/laravel-scout-mysql-driver#113]
More than an issue, a simple question,
Will it support Laravel 8?

Thanks in advance

**Comment by creativewebcode** [comment]
yes

**Comment by jasperf** [comment]
Was just looking for a MySQL driver and read about this Laravel Scout MySQL Driver, but it seems to not support Laravel 8 which cam out a while ago. Any chance this is getting updated any time soon this 2021?

**Comment by msonowal** [comment]
current version supports it
