### ISSUE TITLE
General problem when searching

### ISSUE THREAD

**Issue by rico** [YABhq/laravel-scout-mysql-driver#28]
I have a general problem when searching with this package. For example when I search for `Barbara` -  when the search term is `Ba`, the Barbara's are found, with `Barb` I get no results. Even with `Barbara` as the search term, nothing is found.

I'm running:

 - Laravel 5.3.31
 - scout    2.0.2
 - PHP 7.0.15
 - MariaDB 10.1.20

... and use the default config:

```
'mysql' => [
	    'mode' => 'NATURAL_LANGUAGE',
	    'model_directories' => [app_path() . '/Models'],
	    'min_search_length' => 0,
	    'min_fulltext_search_length' => 4,
	    'min_fulltext_search_fallback' => 'LIKE',
	    'query_expansion' => false
    ]
```

**Comment by jonathan-bird** [comment]
Also noticed and been having this issue with my implementation.

**Comment by jonathan-bird** [comment]
@rico Although probably too late for you now, I found that the fix for me was changing the mode from Natural Language to LIKE. As you can see, the fallback was LIKE for under 4 chars, so that's why that was returning good results, and same with full match but in between was having issues.

**Comment by rico** [comment]
@jonathan-bird thanks for the info, will try!

**Comment by cossou** [comment]
Hi @rico & @jonathan-bird 

Just run into the same issue and it seems like we didn't RTFM. 😄 

To use **NATURAL_LANGUAGE** you need a **FULLTEXT** index. You can do so by using this command:

```php artisan scout:mysql-index App\\MODEL```

Look at https://github.com/damiantw/laravel-scout-mysql-driver#console-command-

**Comment by msonowal** [comment]
seems like you got the help needed
