### ISSUE TITLE
QueryException

### ISSUE THREAD

**Issue by alkhachatryan** [YABhq/laravel-scout-mysql-driver#32]
Hello. I use Laravel 5.3 upgraded to 5.4. I have PHP7 version and Mysql. I run my app on Ubuntu, apache2 machine.
I want search users using your package, when I try with only name (or last name) it's ok, but when I write name and last name, for example John Smith, I get issue.

(2/2) QueryExceptionSQLSTATE[HY000]: General error: 1191 Can't find FULLTEXT index matching the column list (SQL: select count(*) as aggregate from `ys_users` where MATCH(name,last_name,login,password,email,mobile,skype,street,city,file) AGAINST(John Smith IN BOOLEAN MODE))
--

**Comment by msonowal** [comment]
Please mention how to re-produce

**Comment by cocochepeau** [comment]
Just to be sure. Did you run the console command as described in `README.md`?

`php artisan scout:mysql-index`

**Comment by Barcelonczyk** [comment]
I'm pretty sure you didn't create fulltext indexes.

**Comment by Sotatek-HenryPham** [comment]
@msonowal 

```php

class Shop extends Model
{
    use Searchable;

    public function toSearchableArray()
    {
        return [
            'name' => $this->name,
            'tel' => $this->tel,
            'email' => $this->email,
        ];
    }
}
```
![screen shot 2018-07-04 at 11 55 54 am](https://user-images.githubusercontent.com/25896269/42257560-3bcb48ac-7f81-11e8-9f00-38905f7ba70e.png)

![1](https://user-images.githubusercontent.com/25896269/42257599-6ab69e1e-7f81-11e8-87f6-fcd2ef483218.gif)

I created the fulltext indexes but can't search :(

**Comment by bilalswiftsolutions** [comment]
Hey I want to index only limited column and that's because I am also getting this error
