### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by vswarte** [YABhq/laravel-scout-mysql-driver#35]
5.5 will hit fairly soon. Any plans on adding it to the semver in the `composer.json` ?
It seems to be working perfectly fine under 5.5 already, but my tests are probably inadequate.

**Comment by hmazter** [comment]
I submitted PR #36

**Comment by vswarte** [comment]
Brilliant, closing this.

**Comment by c4l3b** [comment]
Is this going to get tagged and released? 5.5 was officially released today
