### ISSUE TITLE
Limitation of results by relevance

### ISSUE THREAD

**Issue by abufalbo** [yabhq/laravel-scout-mysql-driver#41]
Hi,
is it posible to limit of results by relevance?
Something like:

```
SELECT *, MATCH(name,title,text) AGAINST('some text' IN BOOLEAN MODE) AS relevance 
FROM `search_articles`
WHERE MATCH(name,title,text) AGAINST('some text' IN BOOLEAN MODE) 
HAVING relevance > 10 
ORDER BY relevance DESC
```

Thanks

**Comment by mikerockett** [comment]
This would be a great addition — in need of this myself...

**Comment by msonowal** [comment]
@abufalbo 
Please send a PR

**Comment by AurelienMendes** [comment]
The PR #91 may partially help you ... since the Models in the result collection will have now the relevance information as an attribute so that you we be able to filter on this attribute (but in PHP part)
