### ISSUE TITLE
Please update it at packagist.org for laravel 5.5

### ISSUE THREAD

**Issue by sanjayojha** [YABhq/laravel-scout-mysql-driver#45]
Hello there, we are facing problem while updating to laravel 5.5 due to this package. It is updated at github but not at packagist.org.

**Comment by hmazter** [comment]
One temporary workaround is to use dev-master instead of a release version.
I know this is not optimal, but at least it does not block you from upgrading to Laravel 5.5

**Comment by sanjayojha** [comment]
@hmazter 
Exactly what I did after waiting for response.

**Comment by msonowal** [comment]
It's updated eb8c0070157b321e2e631907cd20f9cbc18e7c4c
