### ISSUE TITLE
Appending an accessor throws an error

### ISSUE THREAD

**Issue by djekl** [YABhq/laravel-scout-mysql-driver#46]
If in a model I use `protected $appends` to add say a computed field like `full_address` then you will get

```Undefined offset: 0 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 0 at .../vendor/yab/laravel-scout-mysql-driver/src/Services/ModelService.php:44)```

Will submit a simple PR that will fix this now

**Comment by msonowal** [comment]
Fixes applied in v2.0.1
