### ISSUE TITLE
Relevance as an attribute in model

### ISSUE THREAD

**Issue by keradan** [yabhq/laravel-scout-mysql-driver#53]
I am searching in few models, for example in tables 'posts' and 'categories'. In each separately relevance works good, but I get 2 collections, so order of rows depends on what collection I view first. Is there a way to get relevance attribute to sort merged collections by it?

**Comment by AurelienMendes** [comment]
I've just proposed a merge request to do that ... https://github.com/yabhq/laravel-scout-mysql-driver/pull/91
