### ISSUE TITLE
Search within multiple tables/models

### ISSUE THREAD

**Issue by basvandertogt** [yabhq/laravel-scout-mysql-driver#61]
Is it possible to search within multiple tables/models and get the result in a singel collection? I can't find something about it in the manual.

**Comment by kolotovio** [comment]
> Is it possible to search within multiple tables/models and get the result in a singel collection? I can't find something about it in the manual.

For get results in single collection use mysql union. Tutorial is [here](https://itsolutionstuff.com/post/how-to-use-union-query-with-laravel-eloquentexample.html)

**Comment by z-h-z-h** [comment]
@kolotovio So need to use laravel query builder without $model->search()?

**Comment by notflip** [comment]
Has anyone found a solution to this?
