### ISSUE TITLE
Support for Laravel 5.6

### ISSUE THREAD

**Issue by alijmlzd** [YABhq/laravel-scout-mysql-driver#62]
Hi,

Do you have any plan to support laravel 5.6?

Thank You

**Comment by seanmi** [comment]
Hello,

Please make it available in laravel 5.6

Br,

**Comment by frknasir** [comment]
when will this be updated to support the laravel versions?

**Comment by msonowal** [comment]
@frknasir 
It is already updated to support.
Let me know which versions are having issues if possible send a PR

**Comment by Deadpoolddt** [comment]
Getting this after running: composer require yab/laravel-scout-mysql-driver

Using:  laravel/framework v5.6.27

![image](https://user-images.githubusercontent.com/22669999/44685877-2dd70680-aa12-11e8-9f8b-d30e9795fcbd.png)

**Comment by seanmi** [comment]
I am also getting that error on laravel 5.6

**Comment by frknasir** [comment]
@msonowal Laravel v5.6.31 and v5.6.35

**Comment by domainregistrar** [comment]
I don't think this is actually an issue with Laravel 5.6, it's Scout - I had to drop scout down to 4.0 in order to get this to work.

Working on Laravel 5.6.35 and Scout 4.0 for me.
