### ISSUE TITLE
What's Happening? Cant install it in my project.

### ISSUE THREAD

**Issue by frknasir** [YABhq/laravel-scout-mysql-driver#67]
`Using version ^2.0 for yab/laravel-scout-mysql-driver
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install yab/laravel-scout-mysql-driver v2.0.3
    - Installation request for laravel/scout (locked at v5.0.3, required as ^5.0) -> satisfiable by laravel/scout[v5.0.3].
    - Conclusion: remove laravel/framework v5.6.31
    - Conclusion: don't install laravel/framework v5.6.31
    - yab/laravel-scout-mysql-driver v2.0.0 requires laravel/framework 5.3.*|5.4.* -> satisfiable by laravel/framework[5.3.x-dev, 5.4.x-dev].
    - yab/laravel-scout-mysql-driver v2.0.1 requires laravel/framework 5.3.*|5.4.*|5.5.* -> satisfiable by laravel/framework[5.3.x-dev, 5.4.x-dev, 5.5.x-dev].
    - yab/laravel-scout-mysql-driver v2.0.2 requires laravel/framework 5.3.*|5.4.*|5.5.* -> satisfiable by laravel/framework[5.3.x-dev, 5.4.x-dev, 5.5.x-dev].
    - Can only install one of: laravel/framework[5.3.x-dev, v5.6.31].
    - Can only install one of: laravel/framework[5.4.x-dev, v5.6.31].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.6.31].
    - Installation request for laravel/framework (locked at v5.6.31, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.31].
    - Installation request for yab/laravel-scout-mysql-driver ^2.0 -> satisfiable by yab/laravel-scout-mysql-driver[v2.0.0, v2.0.1, v2.0.2, v2.0.3].

Installation failed, reverting ./composer.json to its original content.`

**Comment by markwalet** [comment]
This happens because the last stable release ([v2.0.3](https://github.com/YABhq/laravel-scout-mysql-driver/tree/v2.0.3)) doesn't support Laravel 5.6 yet. The maintainer needs to add a new tag when the `master` branch is stable enough.

For now, you can use the `dev-master` version when installing the package.

**Comment by frknasir** [comment]
Thanks.

**Comment by markwalet** [comment]
Did it work?

**Comment by frknasir** [comment]
how do i use the dev-master? by using this command? `composer require yab/laravel-scout-mysql-driver`

**Comment by markwalet** [comment]
https://stackoverflow.com/questions/40914114/how-to-install-a-specific-version-of-package-using-composer

**Comment by frknasir** [comment]
Nope. It did not work.

**Comment by markwalet** [comment]
I see. It is because Scout has updated to 5.0 recently.

The maintainer should make an update!

**Comment by frknasir** [comment]
hmmm...Thanks for the info.
