### ISSUE TITLE
Cant require it with Laravel 5.7

### ISSUE THREAD

**Issue by victorpfm** [YABhq/laravel-scout-mysql-driver#72]
Getting this error:

```
Problem 1
    - Conclusion: don't install yab/laravel-scout-mysql-driver v2.0.5
    - Installation request for laravel/scout (locked at v5.0.3, required as ^5.0) -> satisfiable by laravel/scout[v5.0.3].
    - Conclusion: remove laravel/framework v5.7.0
    - Conclusion: don't install laravel/framework v5.7.0
```

**Comment by eliyas5044** [comment]
Also please update `laravel/scout: ^5.0`

**Comment by rhenusone** [comment]
?

**Comment by mefenlon** [comment]
I was getting the same issue. Here is my workaround.

In your project composer.json
Edit the laravel/scout line to require v4
"laravel/scout": "^4.0",
run composer install
then run composer require yab/laravel-scout-mysql-driver

**Comment by msonowal** [comment]
As the package is updated it should not be a problem
