### ISSUE TITLE
Declaration of map function

### ISSUE THREAD

**Issue by DariusIII** [YABhq/laravel-scout-mysql-driver#73]
I have just updated to latest version of laravel/scout (5.0.3) and aravel-scout-mysql-driver (2.0.6) and i have started receiving the following error: 

> Declaration of Yab\MySQLScout\Engines\MySQLEngine::map(Laravel\Scout\Builder $builder, $model) must be compatible with Laravel\Scout\Engines\Engine::map(Laravel\Scout\Builder $builder, $results, $model)

**Comment by msonowal** [comment]
@DariusIII its updated
