### ISSUE TITLE
Scout v7 support?

### ISSUE THREAD

**Issue by sburkett** [yabhq/laravel-scout-mysql-driver#81]
Package looks great! But Scout has been updated to v7 ... any chance of getting this package updated to support it? Thanks!!

**Comment by msonowal** [comment]
@sburkett 
sure
and feel free to send a PR

**Comment by olivierdrot** [comment]
Looks like it is supported by the 2.2.0 but not yet available through composer (not present in packagist).

**Comment by oliverpool** [comment]
You can force composer to use github directly, by adding the following lines to your `composer.json`:
```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/yabhq/laravel-scout-mysql-driver"
    }
  ]
```
