### ISSUE TITLE
Use of the deprecated studly_case() helper breaks the library on Laravel 6

### ISSUE THREAD

**Issue by ziabice** [yabhq/laravel-scout-mysql-driver#92]
Into the file `Providers\MySQLScoutServiceProvider` at lines 46 and 47, the use of the deprecated `studly_case` helper breaks library initialization.

How to fix:

Edit the file: `Providers\MySQLScoutServiceProvider.php`

Include this line at the start:

    use Illuminate\Support\Str;

Then edit lines 46 and 47 this way:

    $mode = $engineNamespace.Str::studly(strtolower(config('scout.mysql.mode')));
    $fallbackMode = $engineNamespace.Str::studly(strtolower(config('scout.mysql.min_fulltext_search_fallback')));

**Comment by freezer278** [comment]
https://github.com/yabhq/laravel-scout-mysql-driver/pull/93
